/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [16-1:0] M_gameMachine_outputled;
  wire [16-1:0] M_gameMachine_outputn;
  wire [16-1:0] M_gameMachine_outputp1;
  wire [16-1:0] M_gameMachine_outputp2;
  reg [1-1:0] M_gameMachine_button2;
  reg [1-1:0] M_gameMachine_button3;
  reg [1-1:0] M_gameMachine_button4;
  reg [1-1:0] M_gameMachine_button1;
  reg [1-1:0] M_gameMachine_button5;
  game_miniBeta_1 gameMachine (
    .clk(clk),
    .rst(rst),
    .button2(M_gameMachine_button2),
    .button3(M_gameMachine_button3),
    .button4(M_gameMachine_button4),
    .button1(M_gameMachine_button1),
    .button5(M_gameMachine_button5),
    .outputled(M_gameMachine_outputled),
    .outputn(M_gameMachine_outputn),
    .outputp1(M_gameMachine_outputp1),
    .outputp2(M_gameMachine_outputp2)
  );
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_edge_dt_btn_p1_out;
  reg [1-1:0] M_edge_dt_btn_p1_in;
  edge_detector_3 edge_dt_btn_p1 (
    .clk(clk),
    .in(M_edge_dt_btn_p1_in),
    .out(M_edge_dt_btn_p1_out)
  );
  wire [1-1:0] M_edge_dt_btn_p2_out;
  reg [1-1:0] M_edge_dt_btn_p2_in;
  edge_detector_3 edge_dt_btn_p2 (
    .clk(clk),
    .in(M_edge_dt_btn_p2_in),
    .out(M_edge_dt_btn_p2_out)
  );
  wire [1-1:0] M_edge_dt_btn_p3_out;
  reg [1-1:0] M_edge_dt_btn_p3_in;
  edge_detector_3 edge_dt_btn_p3 (
    .clk(clk),
    .in(M_edge_dt_btn_p3_in),
    .out(M_edge_dt_btn_p3_out)
  );
  wire [1-1:0] M_edge_dt_btn_p4_out;
  reg [1-1:0] M_edge_dt_btn_p4_in;
  edge_detector_3 edge_dt_btn_p4 (
    .clk(clk),
    .in(M_edge_dt_btn_p4_in),
    .out(M_edge_dt_btn_p4_out)
  );
  wire [1-1:0] M_edge_dt_btn_p5_out;
  reg [1-1:0] M_edge_dt_btn_p5_in;
  edge_detector_3 edge_dt_btn_p5 (
    .clk(clk),
    .in(M_edge_dt_btn_p5_in),
    .out(M_edge_dt_btn_p5_out)
  );
  wire [1-1:0] M_btn_cond_p1_out;
  reg [1-1:0] M_btn_cond_p1_in;
  button_conditioner_8 btn_cond_p1 (
    .clk(clk),
    .in(M_btn_cond_p1_in),
    .out(M_btn_cond_p1_out)
  );
  wire [1-1:0] M_btn_cond_p2_out;
  reg [1-1:0] M_btn_cond_p2_in;
  button_conditioner_8 btn_cond_p2 (
    .clk(clk),
    .in(M_btn_cond_p2_in),
    .out(M_btn_cond_p2_out)
  );
  wire [1-1:0] M_btn_cond_p3_out;
  reg [1-1:0] M_btn_cond_p3_in;
  button_conditioner_8 btn_cond_p3 (
    .clk(clk),
    .in(M_btn_cond_p3_in),
    .out(M_btn_cond_p3_out)
  );
  wire [1-1:0] M_btn_cond_p4_out;
  reg [1-1:0] M_btn_cond_p4_in;
  button_conditioner_8 btn_cond_p4 (
    .clk(clk),
    .in(M_btn_cond_p4_in),
    .out(M_btn_cond_p4_out)
  );
  wire [1-1:0] M_btn_cond_p5_out;
  reg [1-1:0] M_btn_cond_p5_in;
  button_conditioner_8 btn_cond_p5 (
    .clk(clk),
    .in(M_btn_cond_p5_in),
    .out(M_btn_cond_p5_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_btn_cond_p1_in = io_button[0+0-:1];
    M_btn_cond_p2_in = io_button[1+0-:1];
    M_btn_cond_p3_in = io_button[2+0-:1];
    M_btn_cond_p4_in = io_button[3+0-:1];
    M_btn_cond_p5_in = io_button[4+0-:1];
    M_edge_dt_btn_p1_in = M_btn_cond_p1_out;
    M_edge_dt_btn_p2_in = M_btn_cond_p2_out;
    M_edge_dt_btn_p3_in = M_btn_cond_p3_out;
    M_edge_dt_btn_p4_in = M_btn_cond_p4_out;
    M_edge_dt_btn_p5_in = M_btn_cond_p5_out;
    M_gameMachine_button1 = M_edge_dt_btn_p1_out;
    M_gameMachine_button2 = M_edge_dt_btn_p2_out;
    M_gameMachine_button3 = M_edge_dt_btn_p3_out;
    M_gameMachine_button4 = M_edge_dt_btn_p4_out;
    M_gameMachine_button5 = M_edge_dt_btn_p5_out;
    io_led[0+7-:8] = M_gameMachine_outputled[0+7-:8];
    io_led[8+7-:8] = M_gameMachine_outputled[8+7-:8];
    io_led[16+7-:8] = M_gameMachine_outputp1[0+7-:8];
  end
endmodule
